branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "Main Pipeline / Validate"
          - "Main Pipeline / Security"
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      lock_branch: false
      allow_fork_syncing: true
      restrictions: null
      required_signatures: true

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "Main Pipeline / Validate"
          - "Main Pipeline / Security"
      enforce_admins: false
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      lock_branch: false
      allow_fork_syncing: true
      restrictions: null
      required_signatures: false
