# Best practices for solo founders in 2025
version: 2
updates:
  # Group all non-major NPM updates together
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" # Start the week with fresh deps
      time: "04:00"
    open-pull-requests-limit: 3
    groups:
      # Group patch & minor updates together
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "@react-native*"
          - "react-native"
      # Keep React Native updates separate for safety
      react-native:
        patterns:
          - "@react-native*"
          - "react-native"
    # Auto-merge safe updates during quiet hours
    auto-merge: true
    auto-merge-conditions:
      - "status-success=ci"
      - "status-success=CodeQL"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Ignore noisy updates that don't affect production
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/*"
      - dependency-name: "prettier"
      - dependency-name: "eslint*"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # Actions are more stable
      time: "04:30"
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
    auto-merge: true
    commit-message:
      prefix: "ci"
