version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "IgorGanapolsky"
    groups:
      expo:
        patterns:
          - "expo*"
      react:
        patterns:
          - "react*"
          - "@react*"
      dev-deps:
        patterns:
          - "@typescript-eslint/*"
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "ci"
    reviewers:
      - "IgorGanapolsky"
    commit-message:
      prefix: "ci"
      include: "scope"
