version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 20
    versioning-strategy: "auto"
    auto-merge: true
    auto-approve: true
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "IgorGanapolsky"
    groups:
      expo:
        patterns:
          - "expo*"
      react:
        patterns:
          - "react*"
          - "@react*"
      dev-deps:
        patterns:
          - "@typescript-eslint/*"
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/New_York"
    auto-merge: true
    auto-approve: true
    labels:
      - "dependencies"
      - "ci"
    reviewers:
      - "IgorGanapolsky"
    commit-message:
      prefix: "ci"
      include: "scope"
