views:
  - name: Development Pipeline
    type: board
    fields:
      - field: Status
        values:
          - Todo
          - In Progress
          - Review
          - Done
      - field: Priority
        values:
          - 🔥 High
          - 🟡 Medium
          - 🟢 Low
      - field: Type
        values:
          - 🐛 Bug
          - ✨ Feature
          - 📝 Documentation
          - 🔧 Maintenance
    filters:
      - field: Type
        operator: in
        value:
          - 🐛 Bug
          - ✨ Feature
          - 🔧 Maintenance

  - name: Bug Tracking
    type: board
    fields:
      - field: Status
        values:
          - Open
          - Investigating
          - Fix Ready
          - Testing
          - Resolved
      - field: Severity
        values:
          - 🔴 Critical
          - 🟠 High
          - 🟡 Medium
          - 🟢 Low
      - field: Environment
        values:
          - Production
          - Staging
          - Development
    filters:
      - field: Type
        operator: equals
        value: 🐛 Bug

  - name: Sprint Planning
    type: table
    fields:
      - Title
      - Status
      - Assignees
      - Labels
      - Story Points
      - Sprint
      - Priority
    filters:
      - field: Sprint
        operator: equals
        value: Current

  - name: Performance Dashboard
    type: table
    fields:
      - Title
      - Type
      - Status
      - Time to Review
      - Time to Merge
      - Test Coverage
      - Bundle Size Impact
    filters:
      - field: Type
        operator: in
        value:
          - 🚀 Performance
          - ⚡️ Optimization

automations:
  - name: Auto Priority
    condition:
      - field: Labels
        operator: contains
        value: security
    actions:
      - field: Priority
        value: 🔥 High

  - name: Auto Review Request
    condition:
      - field: Status
        operator: changed_to
        value: Review
    actions:
      - type: request_review
        team: code-reviewers

  - name: Sprint Auto Close
    condition:
      - field: Sprint End Date
        operator: equals
        value: today
    actions:
      - type: move_remaining
        to: Next Sprint
      - type: generate_report
        template: sprint-summary

  - name: SLA Monitoring
    condition:
      - field: Type
        operator: equals
        value: 🐛 Bug
      - field: Status
        operator: not_equals
        value: Done
      - field: Created
        operator: greater_than
        value: 48h
    actions:
      - type: add_label
        value: sla-alert
      - type: notify
        channel: #incidents
        message: "⚠️ SLA Alert: Bug ticket exceeding 48h resolution time"
