changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features ✨
      labels:
        - enhancement
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bug
        - fix
    - title: Security Updates 🔒
      labels:
        - security
    - title: Performance Improvements ⚡
      labels:
        - performance
    - title: Documentation 📚
      labels:
        - documentation
    - title: Dependencies 📦
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
