repository:
  name: SuperPassword
  description: Secure password management app built with React Native and Expo
  homepage: https://github.com/IgorGanapolsky/SuperPassword
  topics: react-native, expo, password-manager, security, mobile-app
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "validate"
          - "security"
          - "build"
          - "release"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions:
        apps: []
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "validate"
          - "security"
          - "build"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null

labels:
  - name: "breaking-change"
    color: "d73a4a"
    description: "Introduces a breaking change"
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Documentation improvements"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "This doesn't seem right"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "security"
    color: "d73a4a"
    description: "Security related issue or update"
  - name: "performance"
    color: "0e8a16"
    description: "Performance improvements"
  - name: "dependencies"
    color: "0366d6"
    description: "Updates to dependencies"

collaborators:
  - username: IgorGanapolsky
    permission: admin
