visualization_system:
  version: "2025.1"
  engine: "agentic-viz"
  update_frequency: "real-time"

dashboards:
  executive:
    refresh_rate: "5m"
    panels:
      - name: "Project Health Score"
        type: "gauge"
        data_source: "ml_insights.health"
        thresholds:
          critical: 60
          warning: 75
          optimal: 90

      - name: "Risk Analysis"
        type: "matrix"
        data_source: "ml_insights.risks"
        dimensions:
          - "impact"
          - "probability"
          - "detectability"

      - name: "Resource Optimization"
        type: "sankey"
        data_source: "ml_insights.resources"
        flows:
          - "task_allocation"
          - "skill_distribution"
          - "time_utilization"

  technical:
    refresh_rate: "1m"
    panels:
      - name: "Code Quality Trends"
        type: "time_series"
        data_sources:
          - "sonarqube.metrics"
          - "ml_insights.code_health"
        metrics:
          - "complexity"
          - "coverage"
          - "duplication"
          - "maintainability"

      - name: "Performance Analytics"
        type: "heatmap"
        data_source: "perf_analyzer"
        dimensions:
          - "response_time"
          - "resource_usage"
          - "throughput"

      - name: "Security Posture"
        type: "radar"
        data_source: "security_ai"
        metrics:
          - "vulnerability_score"
          - "compliance_level"
          - "threat_detection"
          - "incident_response"

  operational:
    refresh_rate: "30s"
    panels:
      - name: "Sprint Progress"
        type: "burndown"
        data_source: "ml_insights.sprint"
        features:
          - "velocity_prediction"
          - "completion_forecast"
          - "risk_indicators"

      - name: "Team Productivity"
        type: "stream_graph"
        data_source: "ml_insights.productivity"
        dimensions:
          - "code_commits"
          - "issue_resolution"
          - "review_efficiency"

      - name: "Technical Debt"
        type: "treemap"
        data_source: "ml_insights.tech_debt"
        hierarchies:
          - "component"
          - "severity"
          - "age"

interactive_features:
  drill_down:
    enabled: true
    max_depth: 5
    contexts:
      - "code_level"
      - "component_level"
      - "system_level"

  predictions:
    enabled: true
    types:
      - "trend_forecasting"
      - "anomaly_detection"
      - "impact_analysis"

  recommendations:
    enabled: true
    categories:
      - "optimization"
      - "risk_mitigation"
      - "resource_allocation"

alerts:
  visual:
    - type: "flash"
      priority: "critical"
    - type: "pulse"
      priority: "warning"
    - type: "highlight"
      priority: "info"

  interactive:
    - type: "click_through"
      target: "detailed_analysis"
    - type: "hover_detail"
      content: "ml_insights.summary"

accessibility:
  color_schemes:
    - "deuteranopia_safe"
    - "high_contrast"
    - "dark_mode"

  interaction_modes:
    - "keyboard_navigation"
    - "voice_control"
    - "gesture_control"

export_capabilities:
  formats:
    - "pdf"
    - "interactive_html"
    - "power_point"
    - "excel_dashboard"

  scheduling:
    enabled: true
    frequencies:
      - "daily"
      - "weekly"
      - "monthly"
      - "on_demand"
