name: Compatibility Check

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/*.yml"

jobs:
  compatibility:
    name: Check Compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript compatibility
        run: npx tsc --noEmit

      - name: Check Expo compatibility
        run: |
          npm install -g expo-cli
          npx expo doctor

      - name: Run tests
        run: npm test

      - name: Check dependencies
        run: |
          npm audit
          npx license-checker --production --onlyAllow "MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause"
