name: Update Status Badges

on:
  schedule:
    - cron: "*/30 * * * *" # Run every 30 minutes
  workflow_dispatch:
  workflow_run:
    workflows: ["Agent Orchestration System"]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Download Previous Reports
        uses: actions/download-artifact@v3
        with:
          name: agent-insights
          path: reports
        continue-on-error: true

      - name: Generate Badges
        run: |
          # Install badge generation tool
          npm install -g badge-maker

          # Read health score from insights
          HEALTH_SCORE=$(jq -r '.health_score // 0' reports/insights.json 2>/dev/null || echo "0")
          COVERAGE=$(jq -r '.coverage // 0' reports/metrics.json 2>/dev/null || echo "0")

          # Generate badges
          npx badge-maker "health" "$HEALTH_SCORE%" "${HEALTH_SCORE >= 90 ? 'brightgreen' : HEALTH_SCORE >= 70 ? 'yellow' : 'red'}" > badges/health.svg
          npx badge-maker "coverage" "$COVERAGE%" "${COVERAGE >= 80 ? 'brightgreen' : COVERAGE >= 60 ? 'yellow' : 'red'}" > badges/coverage.svg

      - name: Update Repository Status
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add badges/
          git commit -m "chore: update status badges [skip ci]" || echo "No changes to commit"
          git push
