name: Test Simple Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: |
          echo "Test workflow is running"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"
