name: Update Branch Protection Rules

on:
  workflow_dispatch:

jobs:
  update-protection:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      administration: write

    steps:
      - name: Update Branch Protection Rules
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'CI/CD Pipeline / validate',
                  'CI/CD Pipeline / security',
                  'CI/CD Pipeline / build'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1,
                bypass_pull_request_allowances: {
                  users: [],
                  teams: [],
                  apps: ['github-actions[bot]', 'dependabot[bot]']
                }
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              required_linear_history: true,
              allow_auto_merge: true
            });
