name: Generate Vulnerability Report

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  security-report:
    name: Security Scan & Report
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      issues: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=low --sarif-file-output=snyk.sarif
      
      - name: Run GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.24.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'SuperPassword'
          path: '.'
          format: 'SARIF'
          args: >
            --suppression suppression.xml
            --failOnCVSS 7
            --enableRetired
            
      - name: Generate consolidated report
        run: |
          echo "# Security Vulnerability Report" > report.md
          echo "## Summary" >> report.md
          echo "Generated on: $(date)" >> report.md
          echo "" >> report.md
          
          echo "## Snyk Findings" >> report.md
          jq -r '.runs[].results[] | "- " + .level + ": " + .message.text' snyk.sarif >> report.md
          
          echo "" >> report.md
          echo "## Trivy Findings" >> report.md
          jq -r '.runs[].results[] | "- " + .level + ": " + .message.text' trivy-results.sarif >> report.md
          
          echo "" >> report.md
          echo "## OWASP Dependency-Check Findings" >> report.md
          jq -r '.runs[].results[] | "- " + .level + ": " + .message.text' dependency-check-report.sarif >> report.md
      
      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Weekly Security Vulnerability Report
          content-filepath: ./report.md
          labels: security, automated-report
          
      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: '.'
